version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: document_management_db_prod
    environment:
      POSTGRES_DB: ${DB_DATABASE:-document_management_prod}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-postgres}']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    # Production optimizations
    command:
      [
        'postgres',
        '-c',
        'max_connections=200',
        '-c',
        'shared_buffers=256MB',
        '-c',
        'effective_cache_size=1GB',
        '-c',
        'maintenance_work_mem=64MB',
        '-c',
        'checkpoint_completion_target=0.9',
        '-c',
        'wal_buffers=16MB',
        '-c',
        'default_statistics_target=100',
      ]

  # Optional: Redis for session storage/caching in production
  redis:
    image: redis:7-alpine
    container_name: document_management_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_prod_data:
  redis_data:
